version: '3'

services:
  api:
    container_name: thaqalayn-api
    # image: lovemonge3r3/thaqalayn-api:latest
    build: .
    restart: always
    ports:
      -3001:3001
    networks:
      - apinetwork
    environment:
      MONGODB_URI: ${MONGODB_URI}
      PORT: ${PORT}
      CACHE: ${CACHE}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - redis
  # caddy:
  #   container_name: caddy
  #   image: caddy
  #   restart: always
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #   - ./API/deploy/Caddyfile:/etc/caddy/Caddyfile
  #   - ./API/deploy/caddy_data:/data
  #   networks:
  #     - apinetwork
    # labels:
    #   - "com.centurylinklabs.watchtower.enable=false"
  # watchtower:
  #   container_name: watchtower
  #   image: containrrr/watchtower
  #   restart: always
  #   volumes:
  #   - /root/.docker/config.json:/config.json
  #   - /var/run/docker.sock:/var/run/docker.sock
  #   command: --interval 30
  redis:
    container_name: redis
    image: redis/redis-stack-server
    restart: no
    networks:
      - apinetwork
    # labels:
    # - "com.centurylinklabs.watchtower.enable=false"

networks:
  apinetwork: