version: '3'

services:
  api:
    container_name: thaqalayn-api
    image: lovemonge3r3/thaqalayn-api:latest
    restart: always
    networks:
      - apinetwork
  caddy:
    container_name: caddy
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
    - ./API/deploy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - apinetwork
  watchtower:
    container_name: watchtower
    image: watchtower
    restart: always
    volumes:
    - /root/.docker/config.json:/config.json

networks:
  apinetwork:
