version: '3'

services:
  api:
    container_name: thaqalayn-api
    image: lovemonge3r3/thaqalayn-api:latest
    restart: always
    networks:
      - apinetwork
  caddy:
    container_name: caddy
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
    - ./API/deploy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - apinetwork
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
    - /root/.docker/config.json:/config.json
    - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

networks:
  apinetwork: