service: thaqalaynAPI
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  thaqalayn-api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-domain-manager

custom:
  customDomains:
    - rest:
        domainName: www.thaqalayn-api.net
        basePath: ""
        certificateName: "www.thaqalayn-api.net"
        createRoute53Record: true
    - rest:
        domainName: thaqalayn-api.net
        basePath: ""
        certificateName: "thaqalayn-api.net"
        createRoute53Record: true
