service: thaqalaynAPI
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x


functions:
  thaqalayn-api:
    handler: handler.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true