name: Deploy on Push

on:
  push:
    paths:
      - 'API/**'

jobs:
  serverless_deploy:
    runs-on: ubuntu-latest
    name: serverless deploy
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: npm install
    - name: Deploy
      run: |
            npm install
            npm install -g serverless
            cd ${{github.workspace}}/V2/Deploy/
            make deploy_api
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    # - name: Deploy
    #   uses: serverless/github-action@v3.2
    #   with:
    #     args: deploy
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

