name: Weekly Data Update

on:
  schedule:
    - cron: "0 0 * * 0" # This will run the job every Sunday at 00:00
  workflow_dispatch: # This allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    env: # Define environment variables here
      WEBAPP_URL: ${{ secrets.WEBAPP_URL }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      GEMINI_API_KEY: ${{secrets.GEMINI_API_KEY}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Specify the Node.js version

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22" # Specify the Go version

      - name: Run Make Command
        run: |
          cd ${{github.workspace}}/V2/
          make scrape_all datapath=./ThaqalaynData

      - name: Commit and Push new data
        run: |
          cd ${{github.workspace}}/V2/ThaqalaynData/
          git config --global user.name 'Mohammed Arab'
          git config --global user.email 'mohammed.arab.1881@gmail.com'
          git add -A
          git commit -m "Automated data update"
          git push
